services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: app
    working_dir: /app
    volumes:
      - ./app:/app/app
    ports:
      - "3001:3001"
      - "24678:24678"
    environment:
      APP_PORT: ${APP_PORT}
      DATABASE_URL: ${DATABASE_URL}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      COGNITO_CLIENT_ID: ${COGNITO_CLIENT_ID}
      COGNITO_USER_POOL_ID: ${COGNITO_USER_POOL_ID}
      JWT_SECRET: ${JWT_SECRET}
      AWS_SECRET_ID: ${AWS_SECRET_ID}
      IUGU_API_URL: ${IUGU_API_URL}
      IUGU_API_TOKEN: ${IUGU_API_TOKEN}
      NEW_RELIC_NO_CONFIG_FILE: ${NEW_RELIC_NO_CONFIG_FILE}
      NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: ${NEW_RELIC_DISTRIBUTED_TRACING_ENABLED}
      NEW_RELIC_LOG: ${NEW_RELIC_LOG}
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_APP_NAME: ${NEW_RELIC_APP_NAME}
      WINSTON_LOG_LEVEL: ${WINSTON_LOG_LEVEL}
      HOTMART_API_URL: ${HOTMART_API_URL}
      HOTMART_API_BASIC: ${HOTMART_API_BASIC}
      HOTMART_API_CLIENT_ID: ${HOTMART_API_CLIENT_ID}
      HOTMART_API_SECRET: ${HOTMART_API_SECRET}
      BOTMAKER_CLIENT_ID: ${BOTMAKER_CLIENT_ID}
      BOTMAKER_CLIENT_SECRET: ${BOTMAKER_CLIENT_SECRET}
      BOTMAKER_API_URL: ${BOTMAKER_API_URL}
      BOTMAKER_WHATSAPP_CHANNEL_ID: ${BOTMAKER_WHATSAPP_CHANNEL_ID}
      MAUTIC_API_USERNAME: ${MAUTIC_API_USERNAME}
      MAUTIC_API_PASSWORD: ${MAUTIC_API_PASSWORD}
      MAUTIC_API_URL: ${MAUTIC_API_URL}
      YEM_API_BASE_URL: ${YEM_API_BASE_URL}
      YEM_REMIX_COOKIE_SESSION_SECRET: ${YEM_REMIX_COOKIE_SESSION_SECRET}
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}
      SLACK_WEBHOOK_URL_FORMATION: ${SLACK_WEBHOOK_URL_FORMATION}
      HOTMART_HOTTOK: ${HOTMART_HOTTOK}
      HUBLA_TOKEN: ${HUBLA_TOKEN}
    restart: always
