# fly.toml app configuration file generated for yem-web-staging on 2024-03-10T22:14:11-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

primary_region = 'gru'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
